import { Author, Poem } from '@/types';

export interface FamousPoetProfile extends Author {
  titleBadge?: string;
  poems: Poem[];
}

// Comprehensive database of famous historical poets across all dynasties with authentic full collections
export const FAMOUS_POETS_DIRECTORY: FamousPoetProfile[] = [
  // ==================== 先秦：屈原 ====================
  {
    id: 9619,
    name: '屈原',
    dynasty: { id: 1, name: '先秦' },
    titleBadge: '楚辞之祖',
    description: '战国时期楚国诗人、政治家，中国浪漫主义文学奠基人，“楚辞”创立者。其诗情志深沉，文采绚烂。',
    poemCount: 6,
    poems: [
      {
        id: 901001,
        title: '离骚 (节选)',
        author: { id: 9619, name: '屈原' },
        dynasty: { id: 1, name: '先秦' },
        type: { id: 18, name: '楚辞' },
        content: [
          '帝高阳之苗裔兮，朕皇考曰伯庸。',
          '摄提贞于孟陬兮，惟庚寅吾以降。',
          '皇览揆余初度兮，肇锡余以嘉名。',
          '名余曰正则兮，字余曰灵均。',
          '长太息以掩涕兮，哀民生之多艰。',
          '亦余心之所善兮，虽九死其犹未悔。',
        ],
      },
      {
        id: 901002,
        title: '九歌·湘夫人',
        author: { id: 9619, name: '屈原' },
        dynasty: { id: 1, name: '先秦' },
        type: { id: 18, name: '楚辞' },
        content: [
          '帝子降兮北渚，目眇眇兮愁予。',
          '袅袅兮秋风，洞庭波兮木叶下。',
          '登白薠兮骋望，与佳期兮夕张。',
          '鸟何萃兮蘋中，罾何为兮木上？',
        ],
      },
      {
        id: 901003,
        title: '九歌·国殇',
        author: { id: 9619, name: '屈原' },
        dynasty: { id: 1, name: '先秦' },
        type: { id: 18, name: '楚辞' },
        content: [
          '操吴戈兮被犀甲，车错毂兮短兵接。',
          '旌蔽日兮敌若云，矢交坠兮士争先。',
          '诚既勇兮又以武，终刚强兮不可凌。',
          '身既死兮神以灵，魂魄毅兮为鬼雄！',
        ],
      },
      {
        id: 901004,
        title: '九歌·山鬼',
        author: { id: 9619, name: '屈原' },
        dynasty: { id: 1, name: '先秦' },
        type: { id: 18, name: '楚辞' },
        content: [
          '若有人兮山之阿，被薜荔兮带女萝。',
          '既含睇兮又宜笑，子慕予兮善窈窕。',
          '乘赤豹兮从文狸，辛夷车兮结桂旗。',
          '风飒飒兮木萧萧，思公子兮徒离忧。',
        ],
      },
      {
        id: 901005,
        title: '九章·涉江',
        author: { id: 9619, name: '屈原' },
        dynasty: { id: 1, name: '先秦' },
        type: { id: 18, name: '楚辞' },
        content: [
          '余幼好此奇服兮，年既老而不衰。',
          '带长铗之陆离兮，冠切云之崔嵬。',
          '被明月兮珮宝璐，世溷浊而莫余知兮。',
          '吾与重华游兮瑶之圃，登昆仑兮食玉英。',
        ],
      },
      {
        id: 901006,
        title: '天问 (节选)',
        author: { id: 9619, name: '屈原' },
        dynasty: { id: 1, name: '先秦' },
        type: { id: 18, name: '楚辞' },
        content: [
          '曰：遂古之初，谁传道之？',
          '上下未形，何由考之？',
          '冥昭瞢暗，谁能极之？',
          '冯翼惟象，何以识之？',
        ],
      },
    ],
  },
  // ==================== 魏晋：曹操 ====================
  {
    id: 8228,
    name: '曹操',
    dynasty: { id: 3, name: '魏晋' },
    titleBadge: '魏武帝',
    description: '字孟德，东汉末年杰出政治家、文学家，建安文学代表人物。其诗气魄雄伟，慷慨悲凉。',
    poemCount: 5,
    poems: [
      {
        id: 903001,
        title: '短歌行',
        author: { id: 8228, name: '曹操' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '对酒当歌，人生几何！譬如朝露，去日苦多。',
          '慨当以慷，忧思难忘。何以解忧？唯有杜康。',
          '青青子衿，悠悠我心。但为君故，沉吟至今。',
          '呦呦鹿鸣，食野之苹。我有嘉宾，鼓瑟吹笙。',
          '山不厌高，海不厌深。周公吐哺，天下归心。',
        ],
      },
      {
        id: 903002,
        title: '观沧海',
        author: { id: 8228, name: '曹操' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '东临碣石，以观沧海。水何澹澹，山岛竦峙。',
          '树木丛生，百草丰茂。秋风萧瑟，洪波涌起。',
          '日月之行，若出其中；星汉灿烂，若出其里。',
          '幸甚至哉，歌以咏志。',
        ],
      },
      {
        id: 903003,
        title: '龟虽寿',
        author: { id: 8228, name: '曹操' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '神龟虽寿，犹有竟时；螣蛇乘雾，终为土灰。',
          '老骥伏枥，志在千里；烈士暮年，壮心不已。',
          '盈缩之期，不但在天；养怡之福，可得永年。',
          '幸甚至哉，歌以咏志。',
        ],
      },
      {
        id: 903004,
        title: '蒿里行',
        author: { id: 8228, name: '曹操' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '关东有义士，兴兵讨群凶。初期会盟津，乃心在咸阳。',
          '军合力不齐，踌躇而雁行。势利使人争，嗣还自相戕。',
          '铠甲生虮虱，万姓以死亡。白骨露于野，千里无鸡鸣。',
          '生民百遗一，念之断人肠。',
        ],
      },
      {
        id: 903005,
        title: '苦寒行',
        author: { id: 8228, name: '曹操' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '北上太行山，艰哉何巍巍！羊肠坂诘屈，车轮为之摧。',
          '树木何萧瑟，北风声正悲。熊罴对我蹲，虎豹夹路啼。',
          '溪谷少人民，雪落何霏霏！延颈长叹息，远行多所思。',
        ],
      },
    ],
  },
  // ==================== 魏晋：陶渊明 ====================
  {
    id: 9035,
    name: '陶渊明',
    dynasty: { id: 3, name: '魏晋' },
    titleBadge: '五柳先生',
    description: '字元亮，号五柳先生，世称靖节先生。东晋末至南朝宋初期伟大诗人，田园诗派开创者。',
    poemCount: 6,
    poems: [
      {
        id: 903501,
        title: '饮酒·其五',
        author: { id: 9035, name: '陶渊明' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '结庐在人境，而无车马喧。',
          '问君何能尔？心远地自偏。',
          '采菊东篱下，悠然见南山。',
          '山气日夕佳，飞鸟相与还。',
          '此中有真意，欲辨已忘言。',
        ],
      },
      {
        id: 903502,
        title: '归园田居·其一',
        author: { id: 9035, name: '陶渊明' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '少无适俗韵，性本爱丘山。',
          '误落尘网中，一去三十年。',
          '羁鸟恋旧林，池鱼思故渊。',
          '开荒南野际，守拙归园田。',
          '户庭无尘杂，虚室有余闲。',
          '久在樊笼里，复得返自然。',
        ],
      },
      {
        id: 903503,
        title: '归园田居·其三',
        author: { id: 9035, name: '陶渊明' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '种豆南山下，草盛豆苗稀。',
          '晨兴理荒秽，带月荷锄归。',
          '道狭草木长，夕露沾我衣。',
          '衣沾不足惜，但使愿无违。',
        ],
      },
      {
        id: 903504,
        title: '杂诗·其一',
        author: { id: 9035, name: '陶渊明' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '人生无根蒂，飘如陌上尘。',
          '分散逐风转，此已非常身。',
          '落地为兄弟，何必骨肉亲！',
          '盛年不重来，一日难再晨。',
          '及时当勉励，岁月不待人。',
        ],
      },
      {
        id: 903505,
        title: '读山海经·其一',
        author: { id: 9035, name: '陶渊明' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '孟夏草木长，绕屋树扶疏。',
          '众鸟欣有托，吾亦爱吾庐。',
          '既耕亦已种，时还读我书。',
          '微雨从东来，好风与之俱。',
          '泛览周王传，流观山海图。',
          '俯仰终宇宙，不乐复何如？',
        ],
      },
      {
        id: 903506,
        title: '乞食',
        author: { id: 9035, name: '陶渊明' },
        dynasty: { id: 3, name: '魏晋' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '饥来驱我去，不知竟何之。',
          '行行至斯里，叩门拙言辞。',
          '主人解余意，遗赠岂虚来。',
          '谈话穷日夕，觞至辄倾杯。',
          '情深欣到老，敝庐常自怡。',
        ],
      },
    ],
  },
  // ==================== 唐代：李白 ====================
  {
    id: 2045,
    name: '李白',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '诗仙',
    description: '字太白，号青莲居士，唐代伟大的浪漫主义诗人。其诗风豪放飘逸，气吞山河，与杜甫并称“大李杜”。',
    poemCount: 40,
    poems: [
      {
        id: 309946,
        title: '静夜思',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['床前看月光，疑是地上霜。', '举头望山月，低头思故乡。'],
      },
      {
        id: 310001,
        title: '将进酒',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '君不见黄河之水天上来，奔流到海不复回。',
          '君不见高堂明镜悲白发，朝如青丝暮成雪。',
          '人生得意须尽欢，莫使金樽空对月。',
          '天生我材必有用，千金散尽还复来。',
          '烹羊宰牛且为乐，会须一饮三百杯。',
          '岑夫子，丹丘生，将进酒，杯莫停。',
          '与君歌一曲，请君为我倾耳听。',
          '钟鼓馔玉不足贵，但愿长醉不愿醒。',
          '古来圣贤皆寂寞，惟有饮者留其名。',
          '陈王昔时宴平乐，斗酒十千恣欢谑。',
          '主人何为言少钱，径须沽取对君酌。',
          '五花马，千金裘，呼儿将出换美酒，与尔同销万古愁。',
        ],
      },
      {
        id: 310002,
        title: '望庐山瀑布',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '日照香炉生紫烟，遥看瀑布挂前川。',
          '飞流直下三千尺，疑是银河落九天。',
        ],
      },
      {
        id: 310003,
        title: '蜀道难',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '噫吁嚱，危乎高哉！蜀道之难，难于上青天！',
          '蚕丛及鱼凫，开国何茫然！',
          '尔来四万八千岁，不与秦塞通人烟。',
          '西当太白有鸟道，可以横绝峨眉巅。',
          '地崩山摧壮士死，然后天梯石栈相钩连。',
          '上有六龙回日之高标，下有冲波逆折之回川。',
          '黄鹤之飞尚不得过，猿猱欲度愁攀援。',
          '青泥何盘盘，百步九折萦岩峦。',
          '扪参历井仰胁息，以手抚膺坐长叹。',
          '问君西游何时还？畏途巉岩不可攀。',
          '蜀道之难，难于上青天，使人听此凋朱颜！',
        ],
      },
      {
        id: 310004,
        title: '早发白帝城',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '朝辞白帝彩云间，千里江陵一日还。',
          '两岸猿声啼不住，轻舟已过万重山。',
        ],
      },
      {
        id: 310005,
        title: '月下独酌四首 其一',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '花间一壶酒，独酌无相亲。',
          '举杯邀明月，对影成三人。',
          '月既不解饮，影徒随我身。',
          '暂伴月将影，行乐须及春。',
          '我歌月徘徊，我舞影零乱。',
          '醒时同交欢，醉后各分散。',
          '永结无情游，相期邈云汉。',
        ],
      },
      {
        id: 310006,
        title: '行路难三首 其一',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '金樽清酒斗十千，玉盘珍羞直万钱。',
          '停杯投箸不能食，拔剑四顾心茫然。',
          '欲渡黄河冰塞川，将登太行雪满山。',
          '闲来垂钓碧溪上，忽复乘舟梦日边。',
          '行路难，行路难，多歧路，今安在？',
          '长风破浪会有时，直挂云帆济沧海。',
        ],
      },
      {
        id: 310007,
        title: '梦游天姥吟留别',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: [
          '海客谈瀛洲，烟涛微茫信难求；',
          '越人语天姥，云霞明灭或可睹。',
          '天姥连天向天横，势拔五岳掩赤城。',
          '安能摧眉折腰事权贵，使我不得开心颜！',
        ],
      },
      {
        id: 310008,
        title: '独坐敬亭山',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['众鸟高飞尽，孤云独去闲。', '相看两不厌，只有敬亭山。'],
      },
      {
        id: 310010,
        title: '黄鹤楼送孟浩然之广陵',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '故人西辞黄鹤楼，烟花三月下扬州。',
          '孤帆远影碧空尽，唯见长江天际流。',
        ],
      },
      {
        id: 310011,
        title: '赠汪伦',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '李白乘舟将欲行，忽闻岸上踏歌声。',
          '桃花潭水深千尺，不及汪伦送我情。',
        ],
      },
      {
        id: 310014,
        title: '清平调 其一',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '云想衣裳花想容，春风拂槛露华浓。',
          '若非群玉山头见，会向瑶台月下逢。',
        ],
      },
      {
        id: 310015,
        title: '清平调 其二',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '一枝红艳露凝香，云雨巫山枉断肠。',
          '借问汉宫谁得似，可怜飞燕倚新妆。',
        ],
      },
      {
        id: 310016,
        title: '清平调 其三',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '名花倾国两相欢，长得君王带笑看。',
          '解释春风无限恨，沉香亭北倚阑干。',
        ],
      },
      {
        id: 310020,
        title: '渡荆门送别',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '渡远荆门外，来从楚国游。',
          '山随平野尽，江入大荒流。',
          '月下飞天镜，云生结海楼。',
          '仍怜故乡水，万里送行舟。',
        ],
      },
      {
        id: 310022,
        title: '望天门山',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '天门中断楚江开，碧水东流至此回。',
          '两岸青山相对出，孤帆一片日边来。',
        ],
      },
      {
        id: 310023,
        title: '侠客行',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '赵客缦胡缨，吴钩霜雪明。银鞍照白马，飒沓如流星。',
          '十步杀一人，千里不留行。事了拂衣去，深藏身与名。',
          '三杯吐然诺，五岳倒为轻。眼花耳热后，意气素霓生。',
        ],
      },
      {
        id: 310024,
        title: '夜宿山寺',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: [
          '危楼高百尺，手可摘星辰。',
          '不敢高声语，恐惊天上人。',
        ],
      },
      {
        id: 310025,
        title: '关山月',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '明月出天山，苍茫云海间。长风几万里，吹度玉门关。',
          '汉下白登道，胡窥青海湾。由来征战地，不见有人还。',
        ],
      },
      {
        id: 310026,
        title: '春夜洛城闻笛',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '谁家玉笛暗飞声，散入春风满洛城。',
          '此夜曲中闻折柳，何人不起故园情。',
        ],
      },
      // Page 2
      {
        id: 310027,
        title: '长干行二首 其一',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '妾发初覆额，折花门前剧。郎骑竹马来，绕床弄青梅。',
          '同居长干里，两小无嫌猜。十四为君妇，羞颜未尝开。',
        ],
      },
      {
        id: 310028,
        title: '古朗月行',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '小时不识月，呼作白玉盘。',
          '又疑瑶台镜，飞在青云端。',
        ],
      },
      {
        id: 310029,
        title: '秋浦歌十七首 其十四',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['炉火照天地，红星乱紫烟。', '赧郎明月夜，歌曲动寒川。'],
      },
      {
        id: 310030,
        title: '秋浦歌十七首 其十五',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['白发三千丈，缘愁似个长。', '不知明镜里，何处得秋霜。'],
      },
      {
        id: 310032,
        title: '子夜吴歌·秋歌',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['长安一片月，万户捣衣声。', '秋风吹不尽，总是玉关情。'],
      },
      {
        id: 310033,
        title: '子夜吴歌·春歌',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['秦地罗敷女，采桑绿水边。', '素手青条上，红妆白日鲜。'],
      },
      {
        id: 310034,
        title: '子夜吴歌·夏歌',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['镜湖三百里，菡萏发荷花。', '五月西施采，人看隘若耶。'],
      },
      {
        id: 310035,
        title: '子夜吴歌·冬歌',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['明朝驿使发，一夜絮征袍。', '素手抽针冷，那堪把剪刀。'],
      },
      {
        id: 310036,
        title: '与史郎中钦听黄鹤楼上吹笛',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['一为迁客去长沙，西望长安不见家。', '黄鹤楼中吹玉笛，江城五月落梅花。'],
      },
      {
        id: 310037,
        title: '客中行',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['兰陵美酒郁金香，玉碗盛来琥珀光。', '但使主人能醉客，不知何处是他乡。'],
      },
      {
        id: 310038,
        title: '听蜀僧濬弹琴',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['蜀僧抱绿绮，西下峨眉峰。', '为我一挥手，如听万壑松。'],
      },
      {
        id: 310039,
        title: '送友人',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['青山横北郭，白水绕东城。', '此地一为别，孤蓬万里征。'],
      },
      {
        id: 310040,
        title: '登金陵凤凰台',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['凤凰台上凤凰游，凤去台空江自流。', '吴宫花草埋幽径，晋代衣冠成古丘。'],
      },
      {
        id: 310041,
        title: '宣州谢朓楼饯别校书叔云',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: ['抽刀断水水更流，举杯销愁愁更愁。', '人生在世不称意，明朝散发弄扁舟。'],
      },
      {
        id: 310042,
        title: '金陵酒肆留别',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['风吹柳花满店香，吴姬压酒唤客尝。', '请君试问东流水，别意与之谁短长。'],
      },
      {
        id: 310043,
        title: '峨眉山月歌',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['峨眉山月半轮秋，影入平羌江水流。', '夜发清溪向三峡，思君不见下渝州。'],
      },
      {
        id: 310044,
        title: '哭晁卿衡',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['日本晁卿辞帝都，征帆一片绕蓬壶。', '明月不归沉碧海，白云愁色满苍梧。'],
      },
      {
        id: 310045,
        title: '山中问答',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['问余何意栖碧山，笑而不答心自闲。', '桃花流水窅然去，别有天地非人间。'],
      },
      {
        id: 310046,
        title: '劳劳亭',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['天下伤心处，劳劳送客亭。', '春风知别苦，不遣柳条青。'],
      },
      {
        id: 310047,
        title: '独漉篇',
        author: { id: 2045, name: '李白' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['独漉独漉，水深泥浊。', '泥浊尚可，水深杀我。'],
      },
    ],
  },
  // ==================== 唐代：王维 ====================
  {
    id: 7756,
    name: '王维',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '诗佛',
    description: '字摩诘，号摩诘居士，唐代著名诗人、画家。精通诗书画乐，以山水田园诗著称，苏轼赞其“诗中有画，画中有诗”。',
    poemCount: 20,
    poems: [
      {
        id: 300149,
        title: '山居秋暝',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['空山新雨后，天气晚来秋。', '明月松间照，清泉石上流。', '竹喧归浣女，莲动下渔舟。', '随意春芳歇，王孙自可留。'],
      },
      {
        id: 300150,
        title: '相思',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['红豆生南国，春来发几枝。', '愿君多采撷，此物最相思。'],
      },
      {
        id: 300151,
        title: '九月九日忆山东兄弟',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['独在异乡为异客，每逢佳节倍思亲。', '遥知兄弟登高处，遍插茱萸少一人。'],
      },
      {
        id: 300152,
        title: '鹿柴',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['空山不见人，但闻人语响。', '返景入深林，复照青苔上。'],
      },
      {
        id: 300153,
        title: '竹里馆',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['独坐幽篁里，弹琴复长啸。', '深林人不知，明月来相照。'],
      },
      {
        id: 300154,
        title: '鸟鸣涧',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['人闲桂花落，夜静春山空。', '月出惊山鸟，时鸣春涧中。'],
      },
      {
        id: 300155,
        title: '使至塞上',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['单车欲问边，属国过居延。', '征蓬出汉塞，归雁入胡天。', '大漠孤烟直，长河落日圆。', '萧关逢候骑，都护在燕然。'],
      },
      {
        id: 300156,
        title: '送元二使安西',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['渭城朝雨浥轻尘，客舍青青柳色新。', '劝君更尽一杯酒，西出阳关无故人。'],
      },
      {
        id: 300157,
        title: '终南山',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['太乙近天都，连山接海隅。', '白云回望合，青霭入看无。'],
      },
      {
        id: 300158,
        title: '终南别业',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['中岁颇好道，晚家南山陲。', '行到水穷处，坐看云起时。'],
      },
      {
        id: 300159,
        title: '辛夷坞',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['木末芙蓉花，山中发红萼。', '涧户寂无人，纷纷开且落。'],
      },
      {
        id: 300160,
        title: '杂诗三首 其二',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['君自故乡来，应知故乡事。', '来日绮窗前，寒梅著花未？'],
      },
      {
        id: 300161,
        title: '酬张少府',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['晚年唯好静，万事不关心。', '松风吹解带，山月照弹琴。'],
      },
      {
        id: 300162,
        title: '观猎',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['风劲角弓鸣，将军猎渭城。', '回看射雕处，千里暮云平。'],
      },
      {
        id: 300163,
        title: '汉江临眺',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['江流天地外，山色有无中。', '襄阳好风日，留醉与山翁。'],
      },
      {
        id: 300164,
        title: '积雨辋川庄作',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['漠漠水田飞白鹭，阴阴夏木啭黄鹂。', '山中习静朝观槿，松下清斋折露葵。'],
      },
      {
        id: 300165,
        title: '渭川田家',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: ['斜光照墟落，穷巷牛羊归。', '即此羡闲逸，怅然吟式微。'],
      },
      {
        id: 300166,
        title: '少年行四首 其一',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['新丰美酒斗十千，咸阳游侠多少年。', '相逢意气为君饮，系马高楼垂柳边。'],
      },
      {
        id: 300167,
        title: '青溪',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: ['我心素已闲，清川澹如此。', '请留盘石上，垂钓将已矣。'],
      },
      {
        id: 300168,
        title: '临高台',
        author: { id: 7756, name: '王维' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['高台多悲风，朝日照北林。', '愿飞双白鹄，万里同所寻。'],
      },
    ],
  },
  // ==================== 唐代：杜甫 ====================
  {
    id: 3911,
    name: '杜甫',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '诗圣',
    description: '字子美，自号少陵野老，唐代伟大的现实主义诗人。其诗沉郁顿挫，悲悯苍生，被誉为“诗史”。',
    poemCount: 20,
    poems: [
      {
        id: 343366,
        title: '登高',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['风急天高猿啸哀，渚清沙白鸟飞回。', '无边落木萧萧下，不尽长江滚滚来。', '万里悲秋常作客，百年多病独登台。', '艰难苦恨繁霜鬓，潦倒新停浊酒杯。'],
      },
      {
        id: 343367,
        title: '春望',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['国破山河在，城春草木深。', '感时花溅泪，恨别鸟惊心。', '烽火连三月，家书抵万金。', '白头搔更短，浑欲不胜簪。'],
      },
      {
        id: 343368,
        title: '绝句二首 其一',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['两个黄鹂鸣翠柳，一行白鹭上青天。', '窗含西岭千秋雪，门泊东吴万里船。'],
      },
      {
        id: 343369,
        title: '茅屋为秋风所破歌',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: ['安得广厦千万间，大庇天下寒士俱欢颜！风雨不动安如山。', '呜呼！何时眼前突兀见此屋，吾庐独破受冻死亦足！'],
      },
      {
        id: 343370,
        title: '望岳',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: ['岱宗夫如何？齐鲁青未了。', '会当凌绝顶，一览众山小。'],
      },
      {
        id: 343371,
        title: '春夜喜雨',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['好雨知时节，当春乃发生。', '随风潜入夜，润物细无声。'],
      },
      {
        id: 343372,
        title: '蜀相',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['丞相祠堂何处寻，锦官城外柏森森。', '出师未捷身先死，长使英雄泪满襟。'],
      },
      {
        id: 343373,
        title: '闻官军收河南河北',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['剑外忽传收蓟北，初闻涕泪满衣裳。', '白日放歌须纵酒，青春作伴好还乡。'],
      },
      {
        id: 343374,
        title: '旅夜书怀',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['星垂平野阔，月涌大江流。', '飘飘何所似，天地一沙鸥。'],
      },
      {
        id: 343375,
        title: '江畔独步寻花七绝句 其六',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['黄四娘家花满蹊，千朵万朵压枝低。', '留连戏蝶时时舞，自在娇莺恰恰啼。'],
      },
      {
        id: 343376,
        title: '登岳阳楼',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['昔闻洞庭水，今上岳阳楼。', '吴楚东南坼，乾坤日夜浮。'],
      },
      {
        id: 343377,
        title: '客至',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['花径不曾缘客扫，蓬门今始为君开。', '肯与邻翁相对饮，隔篱呼取尽余杯。'],
      },
      {
        id: 343378,
        title: '月夜',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['今夜鄜州月，闺中只独看。', '香雾云鬟湿，清辉玉臂寒。'],
      },
      {
        id: 343379,
        title: '阁夜',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['岁暮阴阳催短景，天涯霜雪霁寒宵。', '五更鼓角声悲壮，三峡星河影动摇。'],
      },
      {
        id: 343380,
        title: '兵车行',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['车辚辚，马萧萧，行人弓箭各在腰。', '边庭流血成海水，武皇开边意未已。'],
      },
      {
        id: 343381,
        title: '赠卫八处士',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: ['人生不相见，动如参与商。', '明日隔山岳，世事两茫茫。'],
      },
      {
        id: 343382,
        title: '前出塞九首 其六',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['挽弓当挽强，用剑当用长。', '射人先射马，擒贼先擒王。'],
      },
      {
        id: 343383,
        title: '江南逢李龟年',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['岐王宅里寻常见，崔九堂前几度闻。', '正是江南好风景，落花时节又逢君。'],
      },
      {
        id: 343384,
        title: '绝句四首 其三',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['两个黄鹂鸣翠柳，一行白鹭上青天。', '窗含西岭千秋雪，门泊东吴万里船。'],
      },
      {
        id: 343385,
        title: '绝句四首 其一',
        author: { id: 3911, name: '杜甫' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['迟日江山丽，春风花草香。', '泥融飞燕子，沙暖睡鸳鸯。'],
      },
    ],
  },
  // ==================== 唐代：白居易 ====================
  {
    id: 9057,
    name: '白居易',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '诗魔',
    description: '字乐天，号香山居士，唐代伟大的现实主义诗人。其诗语言平易通俗，雅俗共赏。',
    poemCount: 20,
    poems: [
      {
        id: 269310,
        title: '赋得古原草送别',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['离离原上草，一岁一枯荣。', '野火烧不尽，春风吹又生。', '远芳侵古道，晴翠接荒城。', '又送王孙去，萋萋满别情。'],
      },
      {
        id: 269311,
        title: '问刘十九',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['绿蚁新醅酒，红泥小火炉。', '晚来天欲雪，能饮一杯无？'],
      },
      {
        id: 269312,
        title: '钱塘湖春行',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['孤山寺北贾亭西，水面初平云脚低。', '几处早莺争暖树，谁家新燕啄春泥。', '乱花渐欲迷人眼，浅草才能没马蹄。', '最爱湖东行不足，绿杨阴里白沙堤。'],
      },
      {
        id: 269313,
        title: '大林寺桃花',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['人间四月芳菲尽，山寺桃花始盛开。', '长恨春归无觅处，不知转入此中来。'],
      },
      {
        id: 269314,
        title: '暮江吟',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['一道残阳铺水中，半江瑟瑟半江红。', '可怜九月初三夜，露似真珠月似弓。'],
      },
      {
        id: 269315,
        title: '忆江南·江南好',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 20, name: '五代词' },
        content: ['江南好，风景旧曾谙。', '日出江花红胜火，春来江水绿如蓝。', '能不忆江南？'],
      },
      {
        id: 269316,
        title: '花非花',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['花非花，雾非雾。', '夜半来，天明去。', '来如春梦几多时？', '去似朝云无觅处。'],
      },
      {
        id: 269317,
        title: '琵琶行 (节选)',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: ['千呼万唤始出来，犹抱琵琶半遮面。', '转轴拨弦三两声，未成曲调先有情。', '嘈嘈切切错杂弹，大珠小珠落玉盘。', '同是天涯沦落人，相逢何必曾相识！'],
      },
      {
        id: 269318,
        title: '长恨歌 (节选)',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: ['回眸一笑百媚生，六宫粉黛无颜色。', '在天愿作比翼鸟，在地愿为连理枝。', '天长地久有时尽，此恨绵绵无绝期。'],
      },
      {
        id: 269319,
        title: '卖炭翁',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: ['卖炭翁，伐薪烧炭南山中。', '满面尘灰烟火色，两鬓苍苍十指黑。', '可怜身上衣正单，心忧炭贱愿天寒。'],
      },
      {
        id: 269320,
        title: '观刈麦',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: ['田家少闲月，五月人倍忙。', '夜来南风起，小麦覆陇黄。', '复有贫妇人，抱子在其旁。'],
      },
      {
        id: 269321,
        title: '邯郸冬至夜思家',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['邯郸驿里逢冬至，抱膝灯前影伴身。', '想得家中夜深坐，还应说着远行人。'],
      },
      {
        id: 269322,
        title: '后宫词',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['泪湿罗巾梦不成，夜深前殿按歌声。', '红颜未老恩先断，斜倚熏笼坐到明。'],
      },
      {
        id: 269323,
        title: '采莲曲',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['菱叶萦波荷飐风，荷花深处小船通。', '逢郎欲语低头笑，碧玉搔头落水中。'],
      },
      {
        id: 269324,
        title: '舟中夜雪',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['江上晚来疏雨过，江边细草带霜滋。', '夜深知雪重，时闻折竹声。'],
      },
      {
        id: 269325,
        title: '春词',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['低花树映小山楼，春入眉峰碧篆浮。', '尽日倚阑看野水，无情燕子自双飞。'],
      },
      {
        id: 269326,
        title: '慈乌夜啼',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: ['慈乌失其母，啼声感人天。', '昼夜不飞去，经年守故林。'],
      },
      {
        id: 269327,
        title: '遗爱寺',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['弄石临溪坐，寻花绕寺行。', '时闻流水声，便作春山想。'],
      },
      {
        id: 269328,
        title: '南湖早春',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['风回云断雨初晴，返照湖边暖复明。', '乱点碎红山杏发，平铺新绿水荇生。'],
      },
      {
        id: 269329,
        title: '自河南经乱关内阻饥',
        author: { id: 9057, name: '白居易' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['时难年荒世业空，弟兄羁旅各西东。', '田园寥落干戈后，骨肉流离道路中。', '吊影分为千里雁，辞根散作九秋蓬。', '共看明月应垂泪，一夜乡心五处同。'],
      },
    ],
  },
  // ==================== 唐代：李商隐 ====================
  {
    id: 3596,
    name: '李商隐',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '玉谿生',
    description: '字义山，号玉谿生，晚唐著名诗人，与杜牧并称“小李杜”。其诗构思奇特，意境深邃，风格绮丽。',
    poemCount: 20,
    poems: [
      {
        id: 359601,
        title: '锦瑟',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '锦瑟无端五十弦，一弦一柱思华年。',
          '庄生晓梦迷蝴蝶，望帝春心托杜鹃。',
          '沧海月明珠有泪，蓝田日暖玉生烟。',
          '此情可待成追忆？只是当时已惘然。',
        ],
      },
      {
        id: 359602,
        title: '夜雨寄北',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '君问归期未有期，巴山夜雨涨秋池。',
          '何当共剪西窗烛，却话巴山夜雨时。',
        ],
      },
      {
        id: 359603,
        title: '无题·相见时难别亦难',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '相见时难别亦难，东风无力百花残。',
          '春蚕到死丝方尽，蜡炬成灰泪始干。',
          '晓镜但愁云鬓改，夜吟应觉月光寒。',
          '蓬山此去无多路，青鸟殷勤为探看。',
        ],
      },
      {
        id: 359604,
        title: '无题·昨夜星辰昨夜风',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '昨夜星辰昨夜风，画楼西畔桂堂东。',
          '身无彩凤双飞翼，心有灵犀一点通。',
          '隔座送钩春酒暖，分曹射覆蜡灯红。',
          '嗟余听鼓应官去，走马兰台类转蓬。',
        ],
      },
      {
        id: 359605,
        title: '乐游原',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: [
          '向晚意不适，驱车登古原。',
          '夕阳无限好，只是近黄昏。',
        ],
      },
      {
        id: 359606,
        title: '贾生',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '宣室求贤访逐臣，贾生才调更无伦。',
          '可怜夜半虚前席，不问苍生问鬼神。',
        ],
      },
      {
        id: 359607,
        title: '嫦娥',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '云母屏风烛影深，长河渐落晓星沉。',
          '嫦娥应悔偷灵药，碧海青天夜夜心。',
        ],
      },
      {
        id: 359608,
        title: '隋宫',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '乘兴南游不戒严，九重谁省谏书函。',
          '春风举国裁宫锦，半作障泥半作帆。',
          '玉玺不缘归日角，锦帆应是到天涯。',
          '于今腐草无萤火，终古垂杨有暮鸦。',
        ],
      },
      {
        id: 359609,
        title: '安定城楼',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '迢递高城百尺楼，绿杨枝外尽汀洲。',
          '贾生年少虚垂涕，王粲春来更远游。',
          '永忆江湖归白发，欲回天地入扁舟。',
          '不知腐鼠成滋味，猜意鹓雏竟未休。',
        ],
      },
      {
        id: 359610,
        title: '风雨',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '凄凉宝剑篇，羁泊欲穷年。',
          '黄叶仍风雨，青楼自管弦。',
          '新知遭薄俗，旧好隔良缘。',
          '心断新丰酒，销愁又几千。',
        ],
      },
      {
        id: 359611,
        title: '落花',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '高阁客竟去，小园花乱飞。',
          '参差连曲陌，迢递送斜晖。',
          '肠断未忍扫，眼穿仍欲归。',
          '芳心向春尽，所得是沾衣。',
        ],
      },
      {
        id: 359612,
        title: '北青萝',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '残阳西入崦，茅屋访孤僧。',
          '落叶人何在，寒云路几层。',
          '独敲初夜磬，闲倚一枝藤。',
          '世界微尘里，吾宁爱与憎。',
        ],
      },
      {
        id: 359613,
        title: '端居',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '远书归梦两悠悠，只有空床敌素秋。',
          '阶下青苔与红树，雨中寥落月中愁。',
        ],
      },
      {
        id: 359614,
        title: '宿骆氏亭寄怀崔雍崔衮',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '竹坞无尘水槛清，相思迢递隔重城。',
          '秋阴不散霜飞晚，留得枯荷听雨声。',
        ],
      },
      {
        id: 359615,
        title: '蝉',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '本以高难饱，徒劳恨费声。',
          '五更疏欲断，一树碧无情。',
          '薄宦梗犹泛，故园芜已平。',
          '烦君最相警，我亦举家清。',
        ],
      },
      {
        id: 359616,
        title: '凉思',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '客去波涛槛，蝉休雪峤岭。',
          '芦花深泽晚，风起动疏林。',
        ],
      },
      {
        id: 359617,
        title: '寄令狐郎中',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '嵩云秦树久离居，双鲤迢迢一纸书。',
          '休问梁园旧宾客，茂陵秋雨病相如。',
        ],
      },
      {
        id: 359618,
        title: '初食笋呈座中',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '嫩箨香苞初出林，於陵论价贵如金。',
          '皇都陆海应无数，忍剪凌云一寸心。',
        ],
      },
      {
        id: 359619,
        title: '重过圣女祠',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '白石岩扉碧藓滋，半垂蒙密乱芳枝。',
          '蛾眉自有人间嫉，桂魄谁知天上期。',
        ],
      },
      {
        id: 359620,
        title: '无题·重帏深下莫愁堂',
        author: { id: 3596, name: '李商隐' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '重帏深下莫愁堂，卧后清宵细细长。',
          '神女生涯原是梦，小姑居处本无郎。',
          '风波不信菱枝弱，月露谁教桂叶香。',
          '直道相思了无益，未妨惆怅是清狂。',
        ],
      },
    ],
  },
  // ==================== 唐代：杜牧 ====================
  {
    id: 3587,
    name: '杜牧',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '樊川居士',
    description: '字牧之，号樊川居士，晚唐杰出诗人、散文家，与李商隐并称“小李杜”。其诗豪爽清丽，俊拔高迈。',
    poemCount: 20,
    poems: [
      {
        id: 358701,
        title: '清明',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['清明时节雨纷纷，路上行人欲断魂。', '借问酒家何处有？牧童遥指杏花村。'],
      },
      {
        id: 358702,
        title: '山行',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['远上寒山石径斜，白云生处有人家。', '停车坐爱枫林晚，霜叶红于二月花。'],
      },
      {
        id: 358703,
        title: '泊秦淮',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['烟笼寒水月笼沙，夜泊秦淮近酒家。', '商女不知亡国恨，隔江犹唱后庭花。'],
      },
      {
        id: 358704,
        title: '江南春',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['千里莺啼绿映红，水村山郭酒旗风。', '南朝四百八十寺，多少楼台烟雨中。'],
      },
      {
        id: 358705,
        title: '赤壁',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['折戟沉沙铁未销，自将磨洗认前朝。', '东风不与周郎便，铜雀春深锁二乔。'],
      },
      {
        id: 358706,
        title: '过华清宫绝句三首 其一',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['长安回望绣成堆，山顶千门次第开。', '一骑红尘妃子笑，无人知是荔枝来。'],
      },
      {
        id: 358707,
        title: '寄扬州韩绰判官',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['青山隐隐水迢迢，秋尽江南草未凋。', '二十四桥明月夜，玉人何处教吹箫？'],
      },
      {
        id: 358708,
        title: '秋夕',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['银烛秋光冷画屏，轻罗小扇扑流萤。', '天阶夜色凉如水，卧看牵牛织女星。'],
      },
      {
        id: 358709,
        title: '赠别二首 其一',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['娉娉袅袅十三余，豆蔻梢头二月初。', '春风十里扬州路，卷上珠帘总不如。'],
      },
      {
        id: 358710,
        title: '赠别二首 其二',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['多情却似总无情，唯觉樽前笑不成。', '蜡烛有心还惜别，替人垂泪到天明。'],
      },
      {
        id: 358711,
        title: '题乌江亭',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['胜败兵家事不期，包羞忍耻是男儿。', '江东子弟多才俊，卷土重来未可知。'],
      },
      {
        id: 358712,
        title: '金谷园',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['繁华事散逐香尘，流水无情草自春。', '日暮东风怨啼鸟，落花犹似坠楼人。'],
      },
      {
        id: 358713,
        title: '遣怀',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['落魄江湖载酒行，楚腰纤细掌中轻。', '十年一觉扬州梦，赢得青楼薄幸名。'],
      },
      {
        id: 358714,
        title: '叹花',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['自是寻春去较迟，不须惆怅惜芳时。', '狂风落尽深红色，绿叶成阴子满枝。'],
      },
      {
        id: 358715,
        title: '旅宿',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['旅馆无良伴，凝情自悄然。', '寒灯思旧事，断雁警愁眠。'],
      },
      {
        id: 358716,
        title: '登乐游原',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['长空鹏羽阔，宇宙此身轻。', '定水身如絮，喧轩意欲平。'],
      },
      {
        id: 358717,
        title: '齐安郡中偶题二首 其一',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['两竿落日溪桥上，半缕轻烟柳影中。', '多少绿荷相倚恨，一时回首背西风。'],
      },
      {
        id: 358718,
        title: '初冬夜饮',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['淮阳多病偶求欢，客袖侵霜与烛盘。', '砌下梨花一堆雪，明年谁此凭阑干。'],
      },
      {
        id: 358719,
        title: '题宣州开元寺水阁',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['六朝文物草连天，夜半凉风吹水阁。', '江涵秋影雁初飞，与客携壶上翠微。'],
      },
      {
        id: 358720,
        title: '念昔游',
        author: { id: 3587, name: '杜牧' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: ['十载飘然绳检外，樽前自献自为酬。', '秋山春雨闲吟处，倚遍江南寺寺楼。'],
      },
    ],
  },
  // ==================== 唐代：孟浩然 ====================
  {
    id: 3401,
    name: '孟浩然',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '孟襄阳',
    description: '唐代著名山水田园诗人，世称“孟襄阳”。与王维并称“王孟”，诗风清淡自然，意境幽远。',
    poemCount: 15,
    poems: [
      {
        id: 340101,
        title: '春晓',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['春眠不觉晓，处处闻啼鸟。', '夜来风雨声，花落知多少。'],
      },
      {
        id: 340102,
        title: '宿建德江',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['移舟泊烟渚，日暮客愁新。', '野旷天低树，江清月近人。'],
      },
      {
        id: 340103,
        title: '过故人庄',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '故人具鸡黍，邀我至田家。',
          '绿树村边合，青山郭外斜。',
          '开轩面场圃，把酒话桑麻。',
          '待到重阳日，还来就菊花。',
        ],
      },
      {
        id: 340104,
        title: '望洞庭湖赠张丞相',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '八月湖水平，涵虚混太清。',
          '气蒸云梦泽，波撼岳阳城。',
          '欲济无舟楫，端居耻圣明。',
          '坐观垂钓者，徒有羡鱼情。',
        ],
      },
      {
        id: 340105,
        title: '早寒江上有怀',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '木落雁南度，北风江上寒。',
          '我家襄水曲，遥隔楚云端。',
          '乡泪客中尽，孤帆天际看。',
          '迷津欲有问，平海夕漫漫。',
        ],
      },
      {
        id: 340106,
        title: '留别王维',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '寂寂竟何待，朝朝空自归。',
          '欲寻芳草去，惜与故人违。',
          '当路谁相假，知音世所稀。',
          '只应守寂寞，还掩故园扉。',
        ],
      },
      {
        id: 340107,
        title: '夏日南亭怀辛大',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '山光忽西落，池月渐东上。',
          '散发乘夕凉，开轩卧闲敞。',
          '荷风送香气，竹露滴清响。',
          '欲取鸣琴弹，恨无知音赏。',
        ],
      },
      {
        id: 340108,
        title: '宿业师山房待丁大不至',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '夕阳度西岭，群壑倏已暝。',
          '松月生夜凉，风泉满清听。',
          '樵人归欲尽，烟鸟栖初定。',
          '之子期宿来，孤琴候萝径。',
        ],
      },
      {
        id: 340109,
        title: '秋登兰山寄张五',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '北山白云里，隐者自怡悦。',
          '相望始登高，心随雁飞灭。',
          '愁因薄暮起，兴是清秋发。',
          '时见归村人，沙行渡头歇。',
        ],
      },
      {
        id: 340110,
        title: '送杜十四之江南',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '荆吴相接水为乡，君去春江正渺茫。',
          '日暮征帆何处泊，天涯一望断人肠。',
        ],
      },
      {
        id: 340111,
        title: '夜归鹿门山歌',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '山寺钟鸣昼已昏，渔梁渡头争渡喧。',
          '人随沙岸向江村，余亦乘舟归鹿门。',
          '鹿门月照开烟树，忽到庞公栖隐处。',
          '岩扉松径长寂寥，惟有幽人自来去。',
        ],
      },
      {
        id: 340112,
        title: '清明即事',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['帝里重清明，人心自愁思。', '车声上路合，柳色东城翠。'],
      },
      {
        id: 340113,
        title: '洛中访袁拾遗不遇',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['洛阳访才子，江岭作流人。', '闻说梅花早，何如北地春。'],
      },
      {
        id: 340114,
        title: '宴梅道士房',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['林卧愁春尽，开轩览物华。', '忽逢青鸟使，邀访赤松家。'],
      },
      {
        id: 340115,
        title: '洗然弟泽州从事',
        author: { id: 3401, name: '孟浩然' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['怜尔远为客，新从晋水还。', '青云应有路，莫叹鬓毛斑。'],
      },
    ],
  },
  // ==================== 唐代：柳宗元 ====================
  {
    id: 3402,
    name: '柳宗元',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '河东先生',
    description: '字子厚，世称柳河东、柳柳州。唐代文学家、思想家，“唐宋八大家”之一。其诗清冽深邃，意境高洁。',
    poemCount: 12,
    poems: [
      {
        id: 340201,
        title: '江雪',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['千山鸟飞绝，万径人踪灭。', '孤舟蓑笠翁，独钓寒江雪。'],
      },
      {
        id: 340202,
        title: '渔翁',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: [
          '渔翁夜傍西岩宿，晓汲清湘燃楚竹。',
          '烟销日出不见人，欸乃一声山水绿。',
          '回看天际下中流，岩上无心云相逐。',
        ],
      },
      {
        id: 340203,
        title: '溪居',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '久为簪组累，幸此南夷谪。',
          '闲依农圃邻，偶似山林客。',
          '晓耕翻露草，夜榜响溪石。',
          '来往不逢人，长歌楚天碧。',
        ],
      },
      {
        id: 340204,
        title: '登柳州城楼寄漳汀封连四州刺史',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '城上高楼接大荒，海天愁思正茫茫。',
          '惊风乱飐芙蓉水，密雨斜侵薜荔墙。',
          '岭树重遮千里目，江流曲似九回肠。',
          '共来百粤文身地，犹自音书滞一乡。',
        ],
      },
      {
        id: 340205,
        title: '晨诣超师院读禅经',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '汲井漱寒齿，清心拂尘服。',
          '闲持贝叶书，步出东斋读。',
          '真源了无取，妄迹世所逐。',
          '遗言冀可冥，缮性何由熟。',
        ],
      },
      {
        id: 340206,
        title: '酬曹侍御过象县见寄',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '破额山前碧玉流，骚人遥驻木兰舟。',
          '春风无限潇湘意，欲采蘋花不自由。',
        ],
      },
      {
        id: 340207,
        title: '田家三首 其一',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['蓐食晨光起，开门雪满山。', '樵苏随所适，何日复还关。'],
      },
      {
        id: 340208,
        title: '零陵春望',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['谪居犹未白，春色渐苍苍。', '风细花开早，日斜水草香。'],
      },
      {
        id: 340209,
        title: '与浩初上人同看山寄京华亲故',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '海畔尖山似剑铓，秋来处处割愁肠。',
          '若为化得身千亿，散上峰头望故乡。',
        ],
      },
      {
        id: 340210,
        title: '入黄溪闻猿',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 15, name: '五言古诗' },
        content: [
          '溪路翻翻度细草，深林不见行人道。',
          '哀猿一啼天欲暮，客子何由驻征棹。',
        ],
      },
      {
        id: 340211,
        title: '早梅',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['早梅发高树，迥映楚天碧。', '朔风吹落花，清香满虚室。'],
      },
      {
        id: 340212,
        title: '中夜起望西园值月上',
        author: { id: 3402, name: '柳宗元' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['觉来盻庭柯，错落繁星稀。', '虚室古无尘，素月正相辉。'],
      },
    ],
  },
  // ==================== 唐代：王勃 ====================
  {
    id: 3403,
    name: '王勃',
    dynasty: { id: 6, name: '唐' },
    titleBadge: '初唐四杰之首',
    description: '字子安，“初唐四杰”之首。才华横溢，文思敏捷，《滕王阁序》千古传颂。',
    poemCount: 12,
    poems: [
      {
        id: 340301,
        title: '送杜少府之任蜀州',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: [
          '城阙辅三秦，风烟望五津。',
          '与君离别意，同是宦游人。',
          '海内存知己，天涯若比邻。',
          '无为在歧路，儿女共沾巾。',
        ],
      },
      {
        id: 340302,
        title: '滕王阁诗',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '滕王高阁临江渚，佩玉鸣鸾罢歌舞。',
          '画栋朝飞南浦云，珠帘暮卷西山雨。',
          '闲云潭影日悠悠，物换星移几度秋。',
          '阁中帝子今何在？槛外长江空自流。',
        ],
      },
      {
        id: 340303,
        title: '山中',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['长江悲已滞，万里念将归。', '况属高风晚，山山黄叶飞。'],
      },
      {
        id: 340304,
        title: '江亭夜月送别二首 其一',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['江送蜡梅初，舟移桂渚虚。', '天寒流水急，客思望乡余。'],
      },
      {
        id: 340305,
        title: '江亭夜月送别二首 其二',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['乱烟笼碧树，阴月隐清辉。', '别意不堪语，征人何处归。'],
      },
      {
        id: 340306,
        title: '落花落',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: ['落花落，落花纷，风吹落花落何处？昔日青楼倚红袖，今朝枯冢伴黄土。'],
      },
      {
        id: 340307,
        title: '采莲曲',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 16, name: '七言古诗' },
        content: ['采莲归，绿水映红衣。两岸罗衣扑面香，扁舟一叶弄清波。'],
      },
      {
        id: 340308,
        title: '羁春',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 11, name: '五言绝句' },
        content: ['客心伤暮序，宾雁下荒洲。', '还望天涯阔，何处是归舟。'],
      },
      {
        id: 340309,
        title: '蜀中九日',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 12, name: '七言绝句' },
        content: ['九月九日望乡台，他席他乡送客杯。', '人情已向江南去，白雁东飞塞北来。'],
      },
      {
        id: 340310,
        title: '早春野望',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['江旷春潮白，山长晓岫青。', '他乡临睍睆，迟日叹飘零。'],
      },
      {
        id: 340311,
        title: '秋江送别',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 13, name: '五言律诗' },
        content: ['归舟明日发，相送古江滨。', '落日清川里，空余千里人。'],
      },
      {
        id: 340312,
        title: '滕王阁序 (节选名句)',
        author: { id: 3403, name: '王勃' },
        dynasty: { id: 6, name: '唐' },
        type: { id: 23, name: '其他' },
        content: [
          '潦水尽而寒潭清，烟光凝而暮山紫。',
          '落霞与孤鹜齐飞，秋水共长天一色。',
          '渔舟唱晚，响穷彭蠡之滨；雁阵惊寒，声断衡阳之浦。',
          '老当益壮，宁移白首之心？穷且益坚，不坠青云之志。',
        ],
      },
    ],
  },
  // ==================== 宋代：陆游 ====================
  {
    id: 3880,
    name: '陆游',
    dynasty: { id: 8, name: '宋' },
    titleBadge: '放翁',
    description: '字务观，号放翁，南宋著名爱国诗人、词人。其诗作现存九千余首，数量居两宋之冠。风格雄浑豪迈，情感深沉热烈。',
    poemCount: 20,
    poems: [
      {
        id: 388001,
        title: '示儿',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '死去元知万事空，但悲不见九州同。',
          '王师北定中原日，家祭无忘告乃翁。',
        ],
      },
      {
        id: 388002,
        title: '游山西村',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '莫笑农家腊酒浑，丰年留客足鸡豚。',
          '山重水复疑无路，柳暗花明又一村。',
          '箫鼓追随春社近，衣冠简朴古风存。',
          '从今若许闲乘月，拄杖无时夜叩门。',
        ],
      },
      {
        id: 388003,
        title: '钗头凤·红酥手',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '红酥手，黄縢酒，满城春色宫墙柳。',
          '东风恶，欢情薄。一怀愁绪，几年离索。错、错、错。',
          '春如旧，人空瘦，泪痕红浥鲛绡透。',
          '桃花落，闲池阁。山盟虽在，锦书难托。莫、莫、莫！',
        ],
      },
      {
        id: 388004,
        title: '卜算子·咏梅',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '驿外断桥边，寂寞开无主。',
          '已是黄昏独自愁，更著风和雨。',
          '无意苦争春，一任群芳妒。',
          '零落成泥碾作尘，只有香如故。',
        ],
      },
      {
        id: 388005,
        title: '秋夜将晓出篱门迎凉有感',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '三万里河东入海，五千仞岳上摩天。',
          '遗民泪尽胡尘里，南望王师又一年。',
        ],
      },
      {
        id: 388006,
        title: '十一月四日风雨大作二首 其二',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '僵卧孤村不自哀，尚思为国戍轮台。',
          '夜阑卧听风吹雨，铁马冰河入梦来。',
        ],
      },
      {
        id: 388007,
        title: '临安春雨初霁',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '世味年来薄似纱，谁令骑马客京华。',
          '小楼一夜听春雨，深巷明朝卖杏花。',
          '矮纸斜行闲作草，晴窗细乳戏分茶。',
          '素衣莫起风尘叹，犹及清明可到家。',
        ],
      },
      {
        id: 388008,
        title: '沈园二首 其一',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '城上斜阳画角哀，沈园非复旧池台。',
          '伤心桥下春波绿，曾是惊鸿照影来。',
        ],
      },
      {
        id: 388009,
        title: '沈园二首 其二',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '梦断香消四十年，沈祠柳老不吹绵。',
          '此身行作稽山土，犹吊遗踪一泫然。',
        ],
      },
      {
        id: 388010,
        title: '冬夜读书示子聿',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '古人学问无遗力，少壮工夫老始成。',
          '纸上得来终觉浅，绝知此事要躬行。',
        ],
      },
      {
        id: 388011,
        title: '梅花绝句',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '闻道梅花坼晓风，雪堆遍满四山中。',
          '何方可化身千亿，一树梅花一放翁。',
        ],
      },
      {
        id: 388012,
        title: '剑门道中遇微雨',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '衣上征尘杂酒痕，远游无处不消魂。',
          '此身合是诗人未？细雨骑驴入剑门。',
        ],
      },
      {
        id: 388013,
        title: '文章',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 11, name: '五言绝句' },
        content: [
          '文章本天成，妙手偶得之。',
          '粹然无瑕疵，岂复须人为。',
        ],
      },
      {
        id: 388014,
        title: '夜泊水村',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '腰间羽箭久凋零，太息燕然未勒铭。',
          '老子犹堪绝大漠，诸君何至泣新亭。',
          '一身报国有万死，双鬓向人无再青。',
          '便做铁石心肠也，秋风吹泪满衣襟。',
        ],
      },
      {
        id: 388015,
        title: '书愤五首 其一',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '早岁那知世事艰，中原北望气如山。',
          '楼船夜雪瓜洲渡，铁马秋风大散关。',
          '塞上长城空自许，镜中衰鬓已先斑。',
          '出师一表真名世，千载谁堪伯仲间！',
        ],
      },
      {
        id: 388016,
        title: '关山月',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '和戎诏下十五年，将军不战空临边。',
          '朱门沉沉按歌舞，厩马肥死弓断弦。',
          '遗民忍死望恢复，几处今宵垂泪痕！',
        ],
      },
      {
        id: 388017,
        title: '诉衷情·当年万里觅封侯',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '当年万里觅封侯，匹马戍梁州。',
          '关河梦断何处？尘暗旧貂裘。',
          '胡未灭，鬓先秋，泪空流。',
          '此生谁料，心在天山，身老沧洲。',
        ],
      },
      {
        id: 388018,
        title: '鹊桥仙·夜闻杜鹃',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '茅檐人静，蓬窗灯暗，春渚啼莺。',
          '九疑飞翠，三湘送远，天与孤芳。',
        ],
      },
      {
        id: 388019,
        title: '谢池春·壮岁从戎',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '壮岁从戎，曾是气吞残虏。',
          '阵云高、狼烟夜举。朱颜青鬓，拥雕戈西戍。',
        ],
      },
      {
        id: 388020,
        title: '金错刀行',
        author: { id: 3880, name: '陆游' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 17, name: '乐府诗' },
        content: [
          '黄金错刀白玉装，夜穿窗扉出光芒。',
          '丈夫五十功未立，提刀独立顾八荒。',
          '京华结交尽奇士，意气相期共生死。',
        ],
      },
    ],
  },
  // ==================== 宋代：苏轼 ====================
  {
    id: 11678,
    name: '苏轼',
    dynasty: { id: 8, name: '宋' },
    titleBadge: '东坡居士',
    description: '字子瞻，号东坡居士，世称苏东坡。北宋文学家、书画家，“唐宋八大家”之一，豪放词派开创者。',
    poemCount: 20,
    poems: [
      {
        id: 194966,
        title: '水调歌头·明月几时有',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '明月几时有？把酒问青天。',
          '不知天上宫阙，今夕是何年。',
          '我欲乘风归去，又恐琼楼玉宇，高处不胜寒。',
          '起舞弄清影，何似在人间。',
          '转朱阁，低绮户，照无眠。',
          '不应有恨，何事长向别时圆？',
          '人有悲欢离合，月有阴晴圆缺，此事古难全。',
          '但愿人长久，千里共婵娟。',
        ],
      },
      {
        id: 194967,
        title: '定风波·莫听穿林打叶声',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '莫听穿林打叶声，何妨吟啸且徐行。',
          '竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。',
          '料峭春风吹酒醒，微冷，山头斜照却相迎。',
          '回首向来萧瑟处，归去，也无风雨也无晴。',
        ],
      },
      {
        id: 194968,
        title: '念奴娇·赤壁怀古',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '大江东去，浪淘尽，千古风流人物。',
          '故垒西边，人道是，三国周郎赤壁。',
          '乱石穿空，惊涛拍岸，卷起千堆雪。',
          '江山如画，一时多少豪杰。',
          '人生如梦，一尊还酹江月。',
        ],
      },
      {
        id: 194969,
        title: '饮湖上初晴后雨二首 其二',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '水光潋滟晴方好，山色空蒙雨亦奇。',
          '欲把西湖比西子，淡妆浓抹总相宜。',
        ],
      },
      {
        id: 194970,
        title: '题西林壁',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '横看成岭侧成峰，远近高低各不同。',
          '不识庐山真面目，只缘身在此山中。',
        ],
      },
      {
        id: 194971,
        title: '江城子·乙卯正月二十日夜记梦',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '十年生死两茫茫，不思量，自难忘。',
          '千里孤坟，无处话凄凉。',
          '纵使相逢应不识，尘满面，鬓如霜。',
          '相顾无言，惟有泪千行。',
        ],
      },
      {
        id: 194972,
        title: '江城子·密州出猎',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '老夫聊发少年狂，左牵黄，右擎苍，锦帽貂裘，千骑卷平冈。',
          '会挽雕弓如满月，西北望，射天狼。',
        ],
      },
      {
        id: 194973,
        title: '惠崇春江晚景二首 其一',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '竹外桃花三两枝，春江水暖鸭先知。',
          '蒌蒿满地芦芽短，正是河豚欲上时。',
        ],
      },
      {
        id: 194974,
        title: '蝶恋花·春景',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '花褪残红青杏小。燕子飞时，绿水人家绕。',
          '枝上柳绵吹又少。天涯何处无芳草！',
        ],
      },
      {
        id: 194975,
        title: '临江仙·夜归临皋',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '夜饮东坡醒复醉，归来仿佛三更。家童鼻息已雷鸣。敲门都不应，倚杖听江声。',
          '小舟从此逝，江海寄余生。',
        ],
      },
      {
        id: 194976,
        title: '浣溪沙·游蕲水清泉寺',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '山下兰芽短浸溪，松间沙路净无泥，潇潇暮雨子规啼。',
          '谁道人生无再少？门前流水尚能西！休将白发唱黄鸡。',
        ],
      },
      {
        id: 194977,
        title: '赠刘景文',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '荷尽已无擎雨盖，菊残犹有傲霜枝。',
          '一年好景君须记，最是橙黄橘绿时。',
        ],
      },
      {
        id: 194978,
        title: '西江月·世事一场大梦',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '世事一场大梦，人生几度秋凉？夜来风叶已鸣廊。看取眉头鬓上。',
        ],
      },
      {
        id: 194979,
        title: '和子由渑池怀旧',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 14, name: '七言律诗' },
        content: [
          '人生到处知何似，应似飞鸿踏雪泥。',
          '泥上偶然留指爪，鸿飞那复计东西。',
        ],
      },
      {
        id: 194980,
        title: '六月二十七日望湖楼醉书',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '黑云翻墨未遮山，白雨跳珠乱入船。',
          '卷地风来忽吹散，望湖楼下水如天。',
        ],
      },
      {
        id: 194981,
        title: '琴诗',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '若言琴上有琴声，放在匣中何不鸣？',
          '若言声在指头上，何不于君指上听？',
        ],
      },
      {
        id: 194982,
        title: '望江南·超然台作',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '休对故人思故国，且将新火试新茶。诗酒趁年华。',
        ],
      },
      {
        id: 194983,
        title: '减字木兰花·春月',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '春庭月午，摇荡香醪光欲舞。步转回廊，半落梅花婉娩香。',
        ],
      },
      {
        id: 194984,
        title: '鹧鸪天·林断山明竹隐墙',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '村舍外，古城旁。杖藜徐步转斜阳。殷勤昨夜三更雨，又得浮生一日凉。',
        ],
      },
      {
        id: 194985,
        title: '南乡子·重九涵辉楼呈徐君猷',
        author: { id: 11678, name: '苏轼' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '霜降水痕收。浅碧鳞鳞露远洲。酒力渐消风力软，飕飕。破帽多情却恋头。',
          '佳节若为酬。但把清尊断送秋。万事到头都是梦，休休。明日黄花蝶也愁。',
        ],
      },
    ],
  },
  // ==================== 宋代：李清照 ====================
  {
    id: 11433,
    name: '李清照',
    dynasty: { id: 8, name: '宋' },
    titleBadge: '易安居士',
    description: '号易安居士，宋代女词人，婉约词派代表，有“千古第一才女”之称。',
    poemCount: 10,
    poems: [
      {
        id: 245942,
        title: '渔家傲·天接云涛连晓雾',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '天接云涛连晓雾，星河欲转千帆舞。',
          '九万里风鹏正举。风休住，蓬舟吹取三山去！',
        ],
      },
      {
        id: 245943,
        title: '声声慢·寻寻觅觅',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '寻寻觅觅，冷冷清清，凄凄惨惨戚戚。',
          '这次第，怎一个愁字了得！',
        ],
      },
      {
        id: 245944,
        title: '如梦令·昨夜雨疏风骤',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '昨夜雨疏风骤，浓睡不消残酒。',
          '试问卷帘人，却道海棠依旧。',
          '知否，知否？应是绿肥红瘦。',
        ],
      },
      {
        id: 245945,
        title: '如梦令·常记溪亭日暮',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '常记溪亭日暮，沉醉不知归路。',
          '争渡，争渡，惊起一滩鸥鹭。',
        ],
      },
      {
        id: 245946,
        title: '一剪梅·红藕香残玉簟秋',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '花自飘零水自流。一种相思，两处闲愁。',
          '此情无计可消除，才下眉头，却上心头。',
        ],
      },
      {
        id: 245947,
        title: '醉花阴·薄雾浓云愁永昼',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '东篱把酒黄昏后，有暗香盈袖。',
          '莫道不销魂，帘卷西风，人比黄花瘦。',
        ],
      },
      {
        id: 245948,
        title: '夏日绝句',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 12, name: '七言绝句' },
        content: [
          '生当作人杰，死亦为鬼雄。',
          '至今思项羽，不肯过江东。',
        ],
      },
      {
        id: 245949,
        title: '武陵春·风住尘香花已尽',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '物是人非事事休，欲语泪先流。',
          '只恐双溪舴艋舟，载不动许多愁。',
        ],
      },
      {
        id: 245950,
        title: '点绛唇·蹴罢秋千',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '见客入来，袜刬金钗溜。和羞走，倚门回首，却把青梅嗅。',
        ],
      },
      {
        id: 245951,
        title: '减字木兰花·卖花担上',
        author: { id: 11433, name: '李清照' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '卖花担上。买得一枝春欲放。泪染轻匀。犹带彤霞晓露痕。',
        ],
      },
    ],
  },
  // ==================== 宋代：辛弃疾 ====================
  {
    id: 8618,
    name: '辛弃疾',
    dynasty: { id: 8, name: '宋' },
    titleBadge: '稼轩居士',
    description: '字幼安，号稼轩，南宋豪放派词人、将领。其词题材广阔，风格沉雄豪迈，气吞万里如虎。',
    poemCount: 8,
    poems: [
      {
        id: 71065,
        title: '破阵子·为陈同甫赋壮词以寄之',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '醉里挑灯看剑，梦回吹角连营。',
          '八百里分麾下炙，五十弦翻塞外声。沙场秋点兵。',
          '了却君王天下事，赢得生前身后名。可怜白发生！',
        ],
      },
      {
        id: 71067,
        title: '青玉案·元夕',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '东风夜放花千树。更吹落、星如雨。',
          '众里寻他千百度。蓦然回首，那人却在，灯火阑珊处。',
        ],
      },
      {
        id: 71068,
        title: '永遇乐·京口北固亭怀古',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '千古江山，英雄无觅孙仲谋处。舞榭歌台，风流总被雨打风吹去。',
          '想当年，金戈铁马，气吞万里如虎。凭谁问：廉颇老矣，尚能饭否？',
        ],
      },
      {
        id: 71069,
        title: '南乡子·登京口北固亭有怀',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '何处望神州？满眼风光北固楼。千古兴亡多少事？悠悠。不尽长江滚滚流。',
        ],
      },
      {
        id: 71070,
        title: '丑奴儿·书博山道中壁',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '少年不识愁滋味，爱上层楼。爱上层楼。为赋新词强说愁。',
          '而今识尽愁滋味，欲说还休。欲说还休。却道天凉好个秋。',
        ],
      },
      {
        id: 71071,
        title: '西江月·夜行黄沙道中',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '明月别枝惊鹊，清风半夜鸣蝉。稻花香里说丰年，听取蛙声一片。',
        ],
      },
      {
        id: 71072,
        title: '菩萨蛮·书江西造口壁',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '青山遮不住，毕竟东流去。江晚正愁余，山深闻鹧鸪。',
        ],
      },
      {
        id: 71073,
        title: '清平乐·村居',
        author: { id: 8618, name: '辛弃疾' },
        dynasty: { id: 8, name: '宋' },
        type: { id: 20, name: '宋词' },
        content: [
          '茅檐低小，溪上青青草。醉里吴音相媚好，白发谁家翁媪？',
          '最喜小儿亡赖，溪头卧剥莲蓬。',
        ],
      },
    ],
  },
  // ==================== 清代：纳兰性德 ====================
  {
    id: 3074,
    name: '纳兰性德',
    dynasty: { id: 10, name: '清' },
    titleBadge: '饮水词人',
    description: '原名纳兰成德，字容若，号楞伽山人，清代著名词人。其词沉郁真切，深婉动人。',
    poemCount: 6,
    poems: [
      {
        id: 910001,
        title: '木兰花·拟古决绝词柬友',
        author: { id: 3074, name: '纳兰性德' },
        dynasty: { id: 10, name: '清' },
        type: { id: 20, name: '宋词' },
        content: [
          '人生若只如初见，何事秋风悲画扇。',
          '等闲变却故人心，却道故人心易变。',
          '骊山语罢清宵半，泪雨零铃终不怨。',
          '何如薄幸锦衣郎，比翼连枝当日愿。',
        ],
      },
      {
        id: 910002,
        title: '长相思·山一程',
        author: { id: 3074, name: '纳兰性德' },
        dynasty: { id: 10, name: '清' },
        type: { id: 20, name: '宋词' },
        content: [
          '山一程，水一程，身向榆关那畔行，夜深千帐灯。',
          '风一更，雪一更，聒碎乡心梦不成，故园无此声。',
        ],
      },
      {
        id: 910003,
        title: '浣溪沙·谁念西风独自凉',
        author: { id: 3074, name: '纳兰性德' },
        dynasty: { id: 10, name: '清' },
        type: { id: 20, name: '宋词' },
        content: [
          '谁念西风独自凉，萧萧黄叶闭疏窗，沉思往事立残阳。',
          '当时只道是寻常。',
        ],
      },
      {
        id: 910004,
        title: '蝶恋花·辛苦最怜天上月',
        author: { id: 3074, name: '纳兰性德' },
        dynasty: { id: 10, name: '清' },
        type: { id: 20, name: '宋词' },
        content: [
          '辛苦最怜天上月，一昔如环，昔昔都成玦。',
        ],
      },
      {
        id: 910005,
        title: '采桑子·明月多情应笑我',
        author: { id: 3074, name: '纳兰性德' },
        dynasty: { id: 10, name: '清' },
        type: { id: 20, name: '宋词' },
        content: [
          '明月多情应笑我，笑我如今。辜负春心，独自闲行独自吟。',
        ],
      },
      {
        id: 910006,
        title: '画堂春·一生一代一双人',
        author: { id: 3074, name: '纳兰性德' },
        dynasty: { id: 10, name: '清' },
        type: { id: 20, name: '宋词' },
        content: [
          '一生一代一双人，争教两处销魂。相思相望不相亲，天为谁春。',
        ],
      },
    ],
  },
];

/**
 * Find poet by name (exact or partial matching)
 */
export function findPoetByName(name: string): FamousPoetProfile | undefined {
  const clean = name.trim().toLowerCase();
  return FAMOUS_POETS_DIRECTORY.find(
    (p) => p.name.toLowerCase().includes(clean) || clean.includes(p.name.toLowerCase())
  );
}

/**
 * Find poem by ID across all directory profiles
 */
export function findPoemById(id: number | string): Poem | undefined {
  const numId = Number(id);
  for (const poet of FAMOUS_POETS_DIRECTORY) {
    const found = poet.poems?.find((p) => p.id === numId);
    if (found) return found;
  }
  return undefined;
}

/**
 * Filter poems by combined criteria (dynasty, type, author)
 */
export function filterPoemsByCriteria(
  dynasty?: string,
  type?: string,
  author?: string,
  page = 1,
  pageSize = 20
): {
  poems: Poem[];
  totalCount: number;
  totalPages: number;
  hasMore: boolean;
} {
  let list: Poem[] = [];

  // If specific author searched
  if (author) {
    const matchedPoet = findPoetByName(author);
    if (matchedPoet && matchedPoet.poems) {
      list = [...matchedPoet.poems];
    } else {
      const cleanAuthor = author.trim().toLowerCase();
      for (const poet of FAMOUS_POETS_DIRECTORY) {
        if (poet.name.toLowerCase().includes(cleanAuthor)) {
          list.push(...poet.poems);
        }
      }
    }
  } else {
    // Gather all available curated poems
    for (const poet of FAMOUS_POETS_DIRECTORY) {
      list.push(...poet.poems);
    }
  }

  // Filter by dynasty
  if (dynasty) {
    list = list.filter((p) => p.dynasty?.name === dynasty);
  }

  // Filter by type
  if (type) {
    if (type === '唐诗') {
      list = list.filter((p) => p.dynasty?.name === '唐');
    } else if (type === '宋词' || type === '五代词') {
      list = list.filter((p) => p.type?.name?.includes('词') || p.type?.name === type);
    } else {
      list = list.filter((p) => p.type?.name === type);
    }
  }

  const totalCount = list.length;
  const totalPages = Math.ceil(totalCount / pageSize) || 1;
  const startIndex = (page - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  const poems = list.slice(startIndex, endIndex);

  return {
    poems,
    totalCount,
    totalPages,
    hasMore: page < totalPages,
  };
}

/**
 * Filter authors by dynasty and query
 */
export function filterAuthorsByCriteria(
  dynasty?: string,
  q?: string,
  page = 1,
  pageSize = 20
): {
  authors: Author[];
  totalCount: number;
  hasMore: boolean;
} {
  let list: Author[] = [...FAMOUS_POETS_DIRECTORY];

  if (dynasty) {
    list = list.filter((a) => a.dynasty?.name === dynasty);
  }

  if (q) {
    const cleanQ = q.trim().toLowerCase();
    list = list.filter((a) => a.name.toLowerCase().includes(cleanQ));
  }

  const totalCount = list.length;
  const startIndex = (page - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  const authors = list.slice(startIndex, endIndex);

  return {
    authors,
    totalCount,
    hasMore: endIndex < totalCount,
  };
}

/**
 * Get poet's poems with real pagination support
 */
export function getPoetPoems(authorName: string, page = 1, pageSize = 20): {
  poems: Poem[];
  totalCount: number;
  totalPages: number;
  hasMore: boolean;
} {
  return filterPoemsByCriteria(undefined, undefined, authorName, page, pageSize);
}
